
# https://wiki.hypr.land/Configuring/

# Please note not all available settings / options are set here.
# For a full list, see the wiki

###################
### MY PROGRAMS ###
###################

$terminal = kitty
$fileManager = yazi
$menu = rofi -show drun
$browser = firefox

source = ~/.config/hypr/conf/monitors.conf

source = ~/.config/hypr/conf/autostart.conf

source = ~/.config/hypr/conf/env.conf

source = ~/.config/hypr/conf/permissions.conf

source = ~/.config/hypr/conf/look.conf

source = ~/.config/hypr/conf/input.conf

source = ~/.config/hypr/conf/keybinds.conf

source = ~/.config/hypr/conf/windows.conf
