# =====================================================================
# HYPRIDLE CONFIGURATION
# =====================================================================
# See https://wiki.hypr.land/Hypr-Ecosystem/hypridle/

general {
    lock_cmd = pidof hyprlock || hyprlock                 # Avoid starting multiple hyprlock instances
    before_sleep_cmd = loginctl lock-session              # Lock the screen before the system suspends
    after_sleep_cmd = hyprctl dispatch dpms on            # Wake up the screen to avoid pressing a key twice
}

# --- 1. Dim Display ---
listener {
    timeout = 150                                         # 2.5 mins
    on-timeout = brightnessctl -s set 10%                 # Dim monitor backlight
    on-resume = brightnessctl -r                          # Restore monitor backlight
}

# --- 2. Lock Screen & Pause Media ---
listener {
    timeout = 300                                         # 5 mins
    on-timeout = loginctl lock-session                    # Lock screen
    on-timeout = loginctl lock-session && playerctl pause # Pause any playing music/video when locked
}

# --- 3. Turn Off Screen ---
listener {
    timeout = 330                                         # 5.5 mins
    on-timeout = hyprctl dispatch dpms off                # Turn off screen
    on-resume = hyprctl dispatch dpms on                  # Turn screen back on
}

# --- 4. Suspend System ---
listener {
    timeout = 1500                                        # 25 mins
    on-timeout = systemctl suspend                        # Suspend the PC
}
