# =====================================================================
# HYPRLAND MASTER CONFIGURATION
# =====================================================================
# See https://wiki.hypr.land/Configuring/Configuring-Hyprland/
# See https://wiki.hypr.land/Configuring/Keywords/

# --- Default Programs ---
$terminal = kitty
$fileManager = nautilus
$menu = rofi -show drun -theme ~/.config/rofi/launcher.rasi
$browser = firefox

# --- Modules Loading ---
source = ~/.config/hypr/conf/monitors.conf
source = ~/.config/hypr/conf/autostart.conf
source = ~/.config/hypr/conf/env.conf
source = ~/.config/hypr/conf/permissions.conf
source = ~/.config/hypr/conf/look.conf
source = ~/.config/hypr/conf/input.conf
source = ~/.config/hypr/conf/keybinds.conf
source = ~/.config/hypr/conf/windows.conf

xwayland {
  force_zero_scaling = true
}
