#################
### AUTOSTART ###
#################

exec-once = swaync & hypridle

# Wallpaper management
exec-once = swww-daemon
exec-once = ~/.config/hypr/swww/set-wallpaper.sh

exec-once = ~/.config/waybar/launch-waybar.sh
