#################
### AUTOSTART ###
#################

exec-once = swaync & hypridle

# Wallpaper management
exec-once = awww-daemon
exec-once = ~/.config/hypr/awww/set-wallpaper.sh

# Waybar launching
exec-once = ~/.config/waybar/launch-waybar.sh
